site_name: Administración de Sistemas Operativos
site_url: https://angelabserrano.github.io/aso/
site_description: Apuntes de Administración de Sistemas Operativos
site_author: Angela B. Serrano

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/img/logoASO.png
  favicon: assets/img/logoASO.png
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: es

nav:
  - Inicio: index.md
  - UT0. Introducción a Git y Github: git/introduccion.md
  - UT1.1. Bash: linux/bash.md
  - UT1.2. Bash Avanzado: linux/bash-avanzado.md
  - UT2. Procesos, Servicios y Automatización: linux/procesos.md
  - UT3. Acceso y Administración Remota en Linux: linux/acceso-remoto.md
  - UT4. Ansible: linux/ansible.md
  - UT5.1. Servicio de Directorio en Linux: linux/directorio.md
  - UT5.2. Samba: linux/samba.md
  - UT6. PowerShell: scripts/powershell.md
  - UT7.1. Directorio Activo en Windows: wserver/directorio-activo.md
  - UT7.2. PowerShell - Directorio Activo: scripts/powershell-directorio.md
  - UT8. Administración en Windows: wserver/administracion.md
  - UT9. Monitorización y Rendimiento del Sistema: linux/monitorizacion.md
  - "Ampliación: Contenedores y orquestación": linux/kubernetes.md
